LOG_INTERVAL: 50
HOOKS:
    - "CheckpointHook"
    - "IterTimerHook"
    - "TextLoggerHook"
    - "TensorboardMetricsLogger"
    - "CocoEvaluator"
PATHS:
    TRAIN_FILE_PATTERN: "/opt/ml/input/data/train/train/train*"
    VAL_FILE_PATTERN: "/opt/ml/input/data/train/val/val*"
    WEIGHTS: "/opt/ml/input/data/train/model/resnet/resnet-nhwc-2018-02-07/model.ckpt-112603"
    VAL_ANNOTATIONS: "/opt/ml/input/data/train/annotations/instances_val2017.json"
    OUT_DIR: "/opt/ml/code/checkpoints/tensorflow_mask_rcnn"
INPUT:
    TRAIN_BATCH_SIZE: 96
    EVAL_BATCH_SIZE: 96
MODEL:
    DENSE:
        PRE_NMS_TOP_N_TRAIN: 2000
        POST_NMS_TOP_N_TRAIN: 1000
    RCNN:
        ROI_HEAD: "StandardRoIHead"
    FRCNN:
        LOSS_TYPE: "giou"
    INFERENCE:
        VISUALIZE_INTERVAL: 500
SOLVER:
    SCHEDULE: "CosineDecay"
    OPTIMIZER: "NovoGrad"
    LR: 0.002
    BETA_1: 0.9
    BETA_2: 0.5
    MAX_ITERS: 1848
    WARMUP_STEPS: 750

